# {{{ prezto
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi
# }}}
# {{{ constants
ING_NETWORK="ENTER"
# }}}
# {{{ aliases
alias f='fasd -f'
alias boweri='bower install'
alias boweru='bower update'
alias jenv_set_java_home='export JAVA_HOME="$HOME/.jenv/versions/`jenv version-name`"'
alias gRaU='git remote add upstream'
# }}}
# {{{ sources
[[ -e $HOME/.secrets ]] && source $HOME/.secrets
[[ -e $HOME/.vi-mode-cursor ]] && source $HOME/.vi-mode-cursor
# }}}
# {{{ functions
function remove_node_modules { rm -rf node_modules* } 
function remove_bower_components { rm -rf bower_components* } 
function reset_bower_components { remove_bower_components && bower install } 
function setup_ing_proxy() { source $HOME/Repositories/ing/scripts/setup_proxy }
function unset_ing_proxy() { source $HOME/Repositories/ing/scripts/unset_proxy }
function link_ing_npmrc() { ln -s $HOME/Repositories/ing/dotfiles/npmrc $HOME/.npmrc }
function unlink_ing_npmrc() { unlink $HOME/.npmrc }
function link_ing_maven_settings() { ln -s $HOME/Repositories/ing/dotfiles/settings.xml $HOME/.m2/settings.xml }
function unlink_ing_maven_settings() { unlink $HOME/.m2/settings.xml }
function link_ing_settings() { link_ing_npmrc; link_ing_maven_settings; }
function unlink_ing_settings() { unlink_ing_npmrc; unlink_ing_maven_settings; }
function ing_ssh() { ssh -t jumphost ssh -t $@ }
# }}}
# {{{ emacs
if [ -n "$INSIDE_EMACS" ]; then
  export EDITOR=emacsclient
  unset zle_bracketed_paste
fi
# }}}
# {{{ node
export NODE_EXTRA_CA_CERTS="/etc/ssl/ing-certs.pem"
# }}}
# {{{ hub
eval "$(hub alias -s)"
# }}}
# {{{ jenv
eval "$(jenv init -)"
jenv_set_java_home
# }}}
# {{{ fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --follow --glob "!.git/*"'
# }}}
# {{{ rvm
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"
# }}}
# {{{ gcloud
source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc'
source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc'
# }}}
# {{{ bat
export BAT_THEME='DarkNeon'
# }}}
# {{{ ing
if [[ $(networksetup -getcurrentlocation) == $ING_NETWORK ]]; then
  setup_ing_proxy
  enable_spotify_proxy
fi
# }}}
# vim:foldmethod=marker:foldlevel=0
